version: '3.8'

services:
  front-end:
    build: frontend/.
    image: web-equipment
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: backend/.
    image: api-equipment
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/test-siemens
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge